---
# tasks file for nginx
- name: install nginx
  apt: name=nginx state=present
  tags: ['packages']

- name: de-activate sites
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
  tags: [ 'configure' ]

- name: configure nginx sites
  template: src="templates/proxy.conf" dest=/etc/nginx/conf.d
  notify: restart nginx
  tags: [ 'configure' ]

- name: activate nginx sites
  template: src=/etc/nginx/conf.d/proxy.conf dest=/etc/nginx/sites-enabled/proxy.conf
  notify: restart nginx
  tags: [ 'configure' ]

- name: ensure nginx started
  service: name=nginx state=started enabled=yes
  tags: [ 'service' ]