---
# tasks file for sonarqube
####N.B: ansible-galaxy collection install community.general on ansible master
- name: tune linux kernel
  include_tasks: "{{ role_path }}/tasks/Debian-setup-linux-kernel-tuning.yml"

---
- name: install packages
  include_tasks: "{{ role_path }}/tasks/Debian-install-packages.yml"

# - name: update-alternatives
#   include_tasks: "{{ role_path }}/tasks/configure-java-symbolic-links.yml"
#   when: "there are more than one options"

- name: install pip2
  include_tasks: "{{ role_path }}/tasks/Debian-install-pip.yml"
  
####N.B: ansible-galaxy collection install community.postgresql ansible master
- name: setup postgreSQL db
  include_tasks: "{{ role_path }}/tasks/Debian-postgresql-configure.yml"

- name: install sonarqube
  include_tasks: "{{ role_path }}/tasks/Debian-install-sonarqube.yml"